// Mocks generated by Mockito 5.4.5 from annotations
// in compman_mobile/test/features/competitions/domain/mock_competitions_repository.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:compman_mobile/core/error/failures.dart' as _i5;
import 'package:compman_mobile/features/competitions/domain/entities/bookmarked_competition.dart'
    as _i8;
import 'package:compman_mobile/features/competitions/domain/entities/competition.dart'
    as _i6;
import 'package:compman_mobile/features/competitions/domain/repositories/competitions_repository.dart'
    as _i2;
import 'package:fpdart/fpdart.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [CompetitionsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCompetitionsRepository extends _i1.Mock
    implements _i2.CompetitionsRepository {
  MockCompetitionsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<_i5.Failure, List<_i6.Competition>>>
      fetchCompetitions() => (super.noSuchMethod(
            Invocation.method(
              #fetchCompetitions,
              [],
            ),
            returnValue: _i3
                .Future<_i4.Either<_i5.Failure, List<_i6.Competition>>>.value(
                _i7.dummyValue<_i4.Either<_i5.Failure, List<_i6.Competition>>>(
              this,
              Invocation.method(
                #fetchCompetitions,
                [],
              ),
            )),
          ) as _i3.Future<_i4.Either<_i5.Failure, List<_i6.Competition>>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, List<_i8.BookmarkedCompetition>>>
      getBookmarkedCompetitions() => (super.noSuchMethod(
            Invocation.method(
              #getBookmarkedCompetitions,
              [],
            ),
            returnValue: _i3.Future<
                _i4.Either<_i5.Failure,
                    List<_i8.BookmarkedCompetition>>>.value(_i7.dummyValue<
                _i4.Either<_i5.Failure, List<_i8.BookmarkedCompetition>>>(
              this,
              Invocation.method(
                #getBookmarkedCompetitions,
                [],
              ),
            )),
          ) as _i3.Future<
              _i4.Either<_i5.Failure, List<_i8.BookmarkedCompetition>>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, _i4.Unit>> bookmarkCompetition(
          _i6.Competition? competition) =>
      (super.noSuchMethod(
        Invocation.method(
          #bookmarkCompetition,
          [competition],
        ),
        returnValue: _i3.Future<_i4.Either<_i5.Failure, _i4.Unit>>.value(
            _i7.dummyValue<_i4.Either<_i5.Failure, _i4.Unit>>(
          this,
          Invocation.method(
            #bookmarkCompetition,
            [competition],
          ),
        )),
      ) as _i3.Future<_i4.Either<_i5.Failure, _i4.Unit>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, _i4.Unit>> removeBookmark(
          String? competitionId) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeBookmark,
          [competitionId],
        ),
        returnValue: _i3.Future<_i4.Either<_i5.Failure, _i4.Unit>>.value(
            _i7.dummyValue<_i4.Either<_i5.Failure, _i4.Unit>>(
          this,
          Invocation.method(
            #removeBookmark,
            [competitionId],
          ),
        )),
      ) as _i3.Future<_i4.Either<_i5.Failure, _i4.Unit>>);
}
