// Mocks generated by Mockito 5.4.6 from annotations
// in compman_mobile/test/core/platform/mock_xcsoar_saf_service.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:typed_data' as _i5;

import 'package:compman_mobile/core/platform/xcsoar_saf_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [XcsoarSafService].
///
/// See the documentation for Mockito's code generation for more information.
class MockXcsoarSafService extends _i1.Mock implements _i2.XcsoarSafService {
  MockXcsoarSafService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<String> pickDirectory() =>
      (super.noSuchMethod(
            Invocation.method(#pickDirectory, []),
            returnValue: _i3.Future<String>.value(
              _i4.dummyValue<String>(
                this,
                Invocation.method(#pickDirectory, []),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<void> writeFile(_i5.Uint8List? bytes, String? filename) =>
      (super.noSuchMethod(
            Invocation.method(#writeFile, [bytes, filename]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<String?> getSafDirectoryUri() =>
      (super.noSuchMethod(
            Invocation.method(#getSafDirectoryUri, []),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<void> clearSafPermission() =>
      (super.noSuchMethod(
            Invocation.method(#clearSafPermission, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<bool> isPackageInstalled(String? packageId) =>
      (super.noSuchMethod(
            Invocation.method(#isPackageInstalled, [packageId]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> canWriteToMediaDir(String? packageId) =>
      (super.noSuchMethod(
            Invocation.method(#canWriteToMediaDir, [packageId]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<String> pickDirectoryForPackage(String? packageId) =>
      (super.noSuchMethod(
            Invocation.method(#pickDirectoryForPackage, [packageId]),
            returnValue: _i3.Future<String>.value(
              _i4.dummyValue<String>(
                this,
                Invocation.method(#pickDirectoryForPackage, [packageId]),
              ),
            ),
          )
          as _i3.Future<String>);
}
