// Mocks generated by Mockito 5.4.5 from annotations
// in compman_mobile/test/features/competitions/data/mock_datasources.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:typed_data' as _i9;

import 'package:compman_mobile/features/competitions/data/datasources/competitions_local_datasource.dart'
    as _i5;
import 'package:compman_mobile/features/competitions/data/datasources/soaringspot_remote_datasource.dart'
    as _i2;
import 'package:compman_mobile/features/competitions/data/datasources/soarscore_remote_datasource.dart'
    as _i7;
import 'package:compman_mobile/features/competitions/data/models/bookmarked_competition_model.dart'
    as _i6;
import 'package:compman_mobile/features/competitions/data/models/competition_model.dart'
    as _i4;
import 'package:compman_mobile/features/competitions/domain/entities/task_info.dart'
    as _i8;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [SoaringSpotRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockSoaringSpotRemoteDataSource extends _i1.Mock
    implements _i2.SoaringSpotRemoteDataSource {
  MockSoaringSpotRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.CompetitionModel>> fetchCompetitions() =>
      (super.noSuchMethod(
            Invocation.method(#fetchCompetitions, []),
            returnValue: _i3.Future<List<_i4.CompetitionModel>>.value(
              <_i4.CompetitionModel>[],
            ),
          )
          as _i3.Future<List<_i4.CompetitionModel>>);

  @override
  _i3.Future<List<String>> fetchClasses(String? competitionUrl) =>
      (super.noSuchMethod(
            Invocation.method(#fetchClasses, [competitionUrl]),
            returnValue: _i3.Future<List<String>>.value(<String>[]),
          )
          as _i3.Future<List<String>>);
}

/// A class which mocks [CompetitionsLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockCompetitionsLocalDataSource extends _i1.Mock
    implements _i5.CompetitionsLocalDataSource {
  MockCompetitionsLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i6.BookmarkedCompetitionModel>> getAll() =>
      (super.noSuchMethod(
            Invocation.method(#getAll, []),
            returnValue: _i3.Future<List<_i6.BookmarkedCompetitionModel>>.value(
              <_i6.BookmarkedCompetitionModel>[],
            ),
          )
          as _i3.Future<List<_i6.BookmarkedCompetitionModel>>);

  @override
  _i3.Future<_i6.BookmarkedCompetitionModel?> getById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue: _i3.Future<_i6.BookmarkedCompetitionModel?>.value(),
          )
          as _i3.Future<_i6.BookmarkedCompetitionModel?>);

  @override
  _i3.Future<void> save(_i6.BookmarkedCompetitionModel? model) =>
      (super.noSuchMethod(
            Invocation.method(#save, [model]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> delete(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [SoarScoreRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockSoarScoreRemoteDataSource extends _i1.Mock
    implements _i7.SoarScoreRemoteDataSource {
  MockSoarScoreRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i8.TaskInfo>> fetchLatestTasks(String? competitionId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchLatestTasks, [competitionId]),
            returnValue: _i3.Future<List<_i8.TaskInfo>>.value(<_i8.TaskInfo>[]),
          )
          as _i3.Future<List<_i8.TaskInfo>>);

  @override
  _i3.Future<_i9.Uint8List> downloadTask(String? taskUrl) =>
      (super.noSuchMethod(
            Invocation.method(#downloadTask, [taskUrl]),
            returnValue: _i3.Future<_i9.Uint8List>.value(_i9.Uint8List(0)),
          )
          as _i3.Future<_i9.Uint8List>);
}
